name: Docker Image CI
env:
  AWS_REGION_NAME: "us-east-2"
  

on: [push]

jobs:
 My Ci test:
    runs-on: ubuntu-latest

    steps:
    - name: Copy repo  
      uses: actions/checkout@v1
        
      

        
       
